language: node_js
node_js:
  - "6"

cache:
  bundler: true
  directories:
  - node_modules
  - app/bower_components

before_script:
  - npm install
  - bower install

script:
  - karma start karma.conf.js --single-run

