language: node_js
node_js:
  - "6"

env:
 - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true

cache:
  bundler: true
  directories:
  - node_modules
  - app/bower_components

before_script:
  - npm install
  - bower install

script:
  - grunt wiredep && karma start --single-run --browsers "PhantomJS"

