language: node_js
node_js:
  - "5"
  - "6"

cache:
  bundler: true
  directories:
  - node_modules
  - app/bower_components

before_script:
  - yarn
  - bower install

script:
  - grunt wiredep && karma start --single-run --browsers PhantomJS

